name: Publish Python Package to Release and PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest 

    permissions:
      contents: write   # 必需，用于向 Release 上传资产
      id-token: write # 必需，用于通过 OIDC 向 PyPI 进行身份验证

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} dist/*
